name: Build Windows Application

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: python -m pip install --upgrade pip pyinstaller

    - name: Build EXE
      run: pyinstaller --onefile --windowed main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DBC_Converter_Windows
        path: dist/main.exe
